[General]
logLevel = 2 #0 trace; 1 debug; 2 info
openMenuButton = 22 #U used for closing too (ESC also closes)
openNextMenuButton = 49 #https://www.creationkit.com/index.php?title=Input_Script (dec values) N=49
pauseGame = true #set to False if you it should be like <= version 0.0.2 (or if you run some kind of SkyrimSouls Setup)
showInventoryStats = true #show can small window in the inventory menu (over the display picture) 
showInventoryStatsAutoOpen = false #if it should auto open or not, can be closed/open with openMenuButton
showInventoryButton = 11 #0(=Zero) currently typing in the searchbar would notice the input
displayPermanentAV = false # if pAV != AV it will be displayed AV/pAV

[Mods]
skyrimUnbound = false #changes the check for thaneOfWhiterun

[specialHandling]
showResistanceCap = true #display fPlayerMaxResistance or fMaxArmorRating when resistance > cap; display will be "cap (resistance)"

[showStatsSpecial]
displayZero = false #do or do not display values if they are 0

[showStatsMenu]
height = 0 #1 #non/disabled(0),player(1),defence(2),attack(3),magic(4),warrior(5),thief(6)
equipedWeight = 0 #1
weight = 0 #1
armor = 2
damage = 3
skillTrainingsThisLevel = 1
health = 2
healthRatePer = 2
magicka = 2
magickaRatePer = 2
stamina = 2
staminaRatePer = 2
resistDamage = 2
resistDisease = 2
resistPoison = 2
resistFire = 2
resistShock = 2
resistFrost = 2
resistMagic = 2
oneHanded = 5
twoHanded = 5
archery = 6
block = 5
smithing = 5
heavyArmor = 5
lightArmor = 5
pickpocket = 6
lockpicking = 6
sneak = 6
alchemy = 6
speech = 6
enchanting = 4
alteration = 4
conjuration = 4
destruction = 4
illusion = 4
restoration = 4
oneHandedPowerMod = 0 #5
twoHandedPowerMod = 0 #5
archeryPowerMod = 0 #6
blockPowerMod = 0 #5
smithingPowerMod = 0 #5
heavyArmorPowerMod = 0 #5
lightArmorPowerMod = 0 #5
pickpocketPowerMod = 0 #6
lockpickingPowerMod = 0 #6
sneakPowerMod = 0 #6
alchemyPowerMod = 0 #6
speechPowerMod = 0 #6
enchantingPowerMod = 0 #4
alterationPowerMod = 0 #4
conjurationPowerMod = 0 #4
destructionPowerMod = 0 #4
illusionPowerMod = 0 #4
restorationPowerMod = 0 #4
speedMult = 1
inventoryWeight = 1
carryWeight = 1
criticalChance = 3
meleeDamage = 0 #3
unarmedDamage = 0 #3
absorbChance = 0 #2
weaponSpeedMult = 3
bowSpeedBonus = 0 #3
shoutRecoveryMult = 1
movementNoiseMult = 1
dragonSouls = 1
combatHealthRegenMultiply = 0 #2
attackDamageMult = 0 #3
reflectDamage = 0 #2
oneHandedMod = 5
twoHandedMod = 5
archeryMod = 6
blockMod = 5
smithingMod = 5
heavyArmorMod = 5
lightArmorMod = 5
pickpocketMod = 6
lockpickingMod = 6
sneakMod = 6
alchemyMod = 6
speechMod = 6
enchantingMod = 4
alterationMod = 4
conjurationMod = 4
destructionMod = 4
illusionMod = 4
restorationMod = 4
damageArrow = 3
damageLeft = 3
leftWeaponSpeedMult = 3
rightItemCharge = 0 #3
leftItemCharge = 0 #3
armorPerks = 2
mass = 0 #1
bowStaggerBonus = 0 #3
bypassVendorKeywordCheck = 0 #1
bypassVendorStolenCheck = 0 #1
weaponReach = 3 #3
weaponReachLeft = 3 #3
weaponBaseDamage = 0 #3
weaponBaseDamageLeft = 0 #3
weaponStagger = 3 #3
weaponStaggerLeft = 3 #3
weaponCritDamageRating = 0 #3
weaponCritDamageRatingLeft = 0 #3
fallDamageMod = 0 #1

[showStatsName]
name = "Name"
race = "Race"
level = "Level"
perkCount = "Open Perks"
height = "Height"
equipedWeight = "Equiped Weight"
weight = "Weight"
armor = "Armor"
damage = "Damage Weapon"
skillTrainingsThisLevel = "Trainings This Level"
health = "Health"
healthRatePer = "Health Rate"
magicka = "Magicka"
magickaRatePer = "Magicka Rate"
stamina = "Stamina"
staminaRatePer = "Stamina Rate"
resistDamage = "Resist Damage"
resistDisease = "Resist Disease"
resistPoison = "Resist Poison"
resistFire = "Resist Fire"
resistShock = "Resist Shock"
resistFrost = "Resist Frost"
resistMagic = "Resist Magic"
oneHanded = "One Handed"
twoHanded = "Two Handed"
archery = "Archery"
block = "Block"
smithing = "Smithing"
heavyArmor = "Heavy Armor"
lightArmor = "Light Armor"
pickpocket = "Pickpocket"
lockpicking = "Lockpicking"
sneak = "Sneak"
alchemy = "Alchemy"
speech = "Speech"
enchanting = "Enchanting"
alteration = "Alteration"
conjuration = "Conjuration"
destruction = "Destruction"
illusion = "Illusion"
restoration = "Restoration"
oneHandedPowerMod = "One Handed Power Mod"
twoHandedPowerMod = "Two Handed Power Mod"
archeryPowerMod = "Archery Power Mod"
blockPowerMod = "Block Power Mod"
smithingPowerMod = "Smithing Power Mod"
heavyArmorPowerMod = "Heavy Armor Power Mod"
lightArmorPowerMod = "Light Armor Power Mod"
pickpocketPowerMod = "Pickpocket Power Mod"
lockpickingPowerMod = "Lockpicking Power Mod"
sneakPowerMod = "Sneak Power Mod"
alchemyPowerMod = "Alchemy Power Mod"
speechPowerMod = "Speech Power Mod"
enchantingPowerMod = "Enchanting Power Mod"
alterationPowerMod = "Alteration Power Mod"
conjurationPowerMod = "Conjuration Power Mod"
destructionPowerMod = "Destruction Power Mod"
illusionPowerMod = "Illusion Power Mod"
restorationPowerMod = "Restoration Power Mod"
speedMult = "Speed"
inventoryWeight = "Inventory Weight"
carryWeight = "Carry Weight"
criticalChance = "Crit. Chance"
meleeDamage = "Melee Damage"
unarmedDamage = "Unarmed Damage"
absorbChance = "Magic Absorb Chance"
weaponSpeedMult = "Weapon Speed"
bowSpeedBonus = "Bow Speed Bonus"
shoutRecoveryMult = "Shout Recovery Multi"
movementNoiseMult = "Noise"
dragonSouls = "Dragon Souls"
combatHealthRegenMultiply = "Combat Health Regen Multi"
attackDamageMult = "Attack Multiplier"
beast = "Beast"
xp = "XP"
reflectDamage = "Reflect Damage"
oneHandedMod = "One Handed Mod"
twoHandedMod = "Two Handed Mod"
archeryMod = "Archery Mod"
blockMod = "Block Mod"
smithingMod = "Smithing Mod"
heavyArmorMod = "Heavy Armor Mod"
lightArmorMod = "Light Armor Mod"
pickpocketMod = "Pickpocket Mod"
lockpickingMod = "Lockpicking Mod"
sneakMod = "Sneak Mod"
alchemyMod = "Alchemy Mod"
speechMod = "Speech Mod"
enchantingMod = "Enchanting Mod"
alterationMod = "Alteration Mod"
conjurationMod = "Conjuration Mod"
destructionMod = "Destruction Mod"
illusionMod = "Illusion Mod"
restorationMod = "Restoration Mod"
damageArrow = "Damage Arrow"
damageLeft = "Damage Weapon Left"
leftWeaponSpeedMult = "Weapon Speed Left"
rightItemCharge = "Item Charge Right"
leftItemCharge = "Item Charge Left"
armorPerks = "Armor rating multiplier"
mass = "Mass"
bowStaggerBonus = "Bow Stagger Bonus"
bypassVendorKeywordCheck = "Vendor any Item"
bypassVendorStolenCheck = "Vendor stolen Item"
weaponReach = "Reach"
weaponReachLeft = "Reach Left"
weaponBaseDamage = "Base Damage"
weaponBaseDamageLeft = "Base Damage Left"
weaponStagger = "Stagger"
weaponStaggerLeft = "Stagger Left"
weaponCritDamageRating = "Critical Damage Rating"
weaponCritDamageRatingLeft = "Critical Damage Rating Left"
fallDamageMod = "Fall Damage Mod"

[showStatsEnding]
height = ""
equipedWeight = ""
weight = ""
healthRatePer = "%"
magickaRatePer = "%"
staminaRatePer = "%"
resistDamage = "%"
resistDisease = "%"
resistPoison = "%"
resistFire = "%"
resistShock = "%"
resistFrost = "%"
resistMagic = "%"
speedMult = "%"
inventoryWeight = ""
carryWeight = ""
criticalChance = "%"
absorbChance = "%"
weaponSpeedMult = "" # should be in %
bowSpeedBonus = ""
shoutRecoveryMult = "%"
movementNoiseMult = "%" # should be in %
combatHealthRegenMultiply = "%" # should be in %
attackDamageMult = "x"
reflectDamage = "%"
oneHandedMod = "%"
twoHandedMod = "%"
archeryMod = "%"
blockMod = "%"
smithingMod = "%"
heavyArmorMod = "%"
lightArmorMod = "%"
pickpocketMod = "%"
lockpickingMod = "%"
sneakMod = "%"
alchemyMod = "%"
speechMod = "%"
enchantingMod = "%"
alterationMod = "%"
conjurationMod = "%"
destructionMod = "%"
illusionMod = "%"
restorationMod = "%"
leftWeaponSpeedMult = "" # should be in %
armorPerks = "%"
fallDamageMod = "%"

[showStatsMultiplier]
weaponSpeedMult = 1 #0 will not work, cause math you know
shoutRecoveryMult = 100
movementNoiseMult = 100
combatHealthRegenMultiply = 100
leftWeaponSpeedMult = 1
armorPerks = 100
fallDamageMod = 100

[showBeastName]
vampire = "Vampire"
werewolf = "Werewolf"

[showFactionsFactionNames]
companions = "Companions"
darkbrotherHood = "The Dark Brotherhood"
collegeOfWinterhold = "College of Winterhold"
orcFriend = "Blood-Kin of the Orcs"
thiefsGuild = "Thieves' Guild"
imperialLegion = "Imperial Legion"
stormcloaks = "Stormcloaks" #sons of skyrim
greybeard = "The Greybeards"
bard = "Bards College"
volkiharVampireClan = "Volkihar Vampire Clan"
dawnguard = "Dawnguard"
houseTelvanni = "House Telvanni"

[showFactionsFactionMenu]
faction = 1 #disabled(0),faction(1),thane(2),champion(3)

[showFactionsFactionRank]
bard = "Bard"
assassin = "Assassin"
listener = "Listener"
auxiliary = "Auxiliary"
quaestor = "Quaestor"
praefect = "Praefect"
tribune = "Tribune"
legate = "Legate"
unblooded = "Unblooded"
iceVeins = "Ice-Veins"
boneBreaker = "Bone-Breaker"
snowHammer = "Snow-Hammer"
stormblade = "Stormblade"
vampireLord = "Vampire Lord"
vampireHunter = "Vampire Hunter"
honoraryMember = "Honorary Member"
ysmir = "Ysmir"

[showFactionsThaneMenu]
thane = 2 #disabled(0),faction(1),thane(2),champion(3)

[showFactionsThaneName]
thaneOfEastmarch = "Thane Of Eastmarch"
thaneOfFalkreath = "Thane Of Falkreath"
thaneOfHaafingar = "Thane Of Haafingar"
thaneOfHjaalmarch = "Thane Of Hjaalmarch"
thaneOfThePale = "Thane Of The Pale"
thaneOfTheReach = "Thane Of The Reach"
thaneOfTheRift = "Thane Of The Rift"
thaneOfWhiterun = "Thane Of Whiterun"
thaneOfWinterhold = "Thane Of Winterhold"

[showFactionsChampionMenu]
champion = 3 #disabled(0),faction(1),thane(2),champion(3)

[showFactionsChampionName]
azura = "Azura"
boethiah = "Boethiah"
clavicusVile = "Clavicus Vile"
hermaeusMora = "Hermaeus Mora"
hircine = "Hircine"
malacath = "Malacath"
mehrunesDagon = "Mehrunes Dagon"
mephala = "Mephala"
meridia = "Meridia"
molagBal = "Molag Bal"
namira = "Namira"
nocturnal = "Nocturnal"
peryite = "Peryite"
sanguine = "Sanguine"
sheogorath = "Sheogorath"
vaermina = "Vaermina"

[showStatsInventorySpecial]
displayZero = false #do or do not display values if they are 0

[showStatsInventoryMenu]
equipedWeight = 0 #2 #non/disabled(0),armor(1),weapon(2),effect(3)
armor = 2
damage = 3
health = 2
healthRatePer = 2
magicka = 2
magickaRatePer = 2
stamina = 2
staminaRatePer = 2
resistDamage = 4
resistDisease = 0 #4
resistPoison = 4
resistFire = 4
resistShock = 4
resistFrost = 4
resistMagic = 4
oneHanded = 0 #4
twoHanded = 0 #4
archery = 0 #4
block = 0 #4
smithing = 0 #4
heavyArmor = 0 #4
lightArmor = 0 #4
pickpocket = 0 #4
lockpicking = 0 #4
sneak = 0 #4
alchemy = 0 #4
speech = 0 #4
enchanting = 0 #4
alteration = 0 #4
conjuration = 0 #4
destruction = 0 #4
illusion = 0 #4
restoration = 0 #4
oneHandedPowerMod = 0 #4
twoHandedPowerMod = 0 #4
archeryPowerMod = 0 #4
blockPowerMod = 0 #4
smithingPowerMod = 0 #4
heavyArmorPowerMod = 0 #4
lightArmorPowerMod = 0 #4
pickpocketPowerMod = 0 #4
lockpickingPowerMod = 0 #4
sneakPowerMod = 0 #4
alchemyPowerMod = 0 #4
speechPowerMod = 0 #4
enchantingPowerMod = 0 #4
alterationPowerMod = 0 #4
conjurationPowerMod = 0 #4
destructionPowerMod = 0 #4
illusionPowerMod = 0 #4
restorationPowerMod = 0 #4
speedMult = 0 #4
inventoryWeight = 0 #4
carryWeight = 0 #4
criticalChance = 3
meleeDamage = 0 #3
unarmedDamage = 0 #3
absorbChance = 0 #2
weaponSpeedMult = 3
bowSpeedBonus = 0 #4
shoutRecoveryMult = 0 #4
movementNoiseMult = 2
attackDamageMult = 0 #4
reflectDamage = 0 #3
oneHandedMod = 4
twoHandedMod = 4
archeryMod = 4
blockMod = 4
smithingMod = 4
heavyArmorMod = 4
lightArmorMod = 4
pickpocketMod = 4
lockpickingMod = 4
sneakMod = 4
alchemyMod = 4
speechMod = 4
enchantingMod = 4
alterationMod = 4
conjurationMod = 4
destructionMod = 4
illusionMod = 4
restorationMod = 4
damageArrow = 3
damageLeft = 3
leftWeaponSpeedMult = 3
rightItemCharge = 0 #3
leftItemCharge = 0 #3
armorPerks = 2
mass = 0 #2
bowStaggerBonus = 0 #4
weaponReach = 3
weaponReachLeft = 3
weaponBaseDamage = 0 #3
weaponBaseDamageLeft = 0 #3
weaponStagger = 3
weaponStaggerLeft = 3
weaponCritDamageRating = 0 #3
weaponCritDamageRatingLeft = 0 #3
fallDamageMod = 0 #4